title: Site

pages: default

fields:
  title:
    label: Title
    type:  text

  subtitle:
    label: Subtitle
    type:  text

  author:
    label: Author
    type:  text
    readonly: true

  description:
    label: Description
    type:  textarea